/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.5
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.cwq.test;

public class TestJNI {
  public final static native void clickButton1(long jarg1);
  public final static native void clickButton2(long jarg1);
}
