/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.5
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.cwq.test;

public class Test {
  public static void clickButton1(long ptr) {
    TestJNI.clickButton1(ptr);
  }

  public static void clickButton2(long ptr) {
    TestJNI.clickButton2(ptr);
  }

}
